[package]
name = "raria-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
base64.workspace = true
bendy.workspace = true
bytes.workspace = true
clap.workspace = true
governor.workspace = true
librqbit.workspace = true
netrc.workspace = true
quick-xml.workspace = true
reqwest.workspace = true
russh.workspace = true
russh-sftp.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
suppaftp.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[dev-dependencies]
anyhow.workspace = true
futures-util.workspace = true
libunftp.workspace = true
rand.workspace = true
tempfile.workspace = true
tokio-tungstenite.workspace = true
unftp-sbe-fs.workspace = true
